navikt/isdialogmotekandidat

src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/DialogmotekandidatEndringProducer.kt
Use UUID based on PersonIdent to ensure that records for a given PersonIdent ends up on the same Kafka partition.
=> Set key of OppfolgingstilfellePerson to UUID created from PersonIdent

src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatStoppunkt.kt
Move Stoppunkt for Dialogmotekandidat from week 16(day 112) to week 17(day 119) to reduce inconsistencies with Arena and avoid generating to many DialogmoteKandidat.
=> Change Stoppunkt from week 16 to week 17

.github/workflows/kafka-dialogmotekandidat-midlertidig.yaml, .nais/kafka/dialogmotekandidat-midlertidig.yaml, README.md
Create a topic to publish Dialogmotekandidat. This topic is created for use by application Syfomotebehov until topic isdialogmotekandidat-dialogmotekandidat is ready for use in Production. When the topic is ready for use, Syfomotebehov can migrate to it and the temporary topic can be deleted after Syfomotebehov has migrated.
=> Create temporary topic for Dialogmotekandidat

.nais/naiserator-prod.yaml
Dette endrer litt på rekkefølgen Erik foreslo, men siden vi nå lagrer statusendringene på dialogmøter i databasen er det bedre å aktivere denne først.
=> Enable Kafka-consumer for dialogmote-statusendring

src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/DialogmotekandidatStoppunktQuery.kt
CURRENT_DATE i databasen kan avvike fra datoen hos oss siden den befinner seg i Finland (og det er mulig den vil bruke UTC for å finne datoen på et gitt tidspunkt). Samme hva er det enklere å forholde seg til lokal dato i Norge denne sammenhengen.
=> Use local date instead of db-currentdate

src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatStoppunkt.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleArbeidstaker.kt, src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmotekandidatGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/KafkaOppfolgingstilfelleArbeidstakerGenerator.kt
Siden cronjob'en prosesserer stoppunkter fra dagens dato må vi unngå å generere stoppunkt tilbake i tid for aktuelle (dvs ikke historiske) oppfølgingstilfeller.
=> Ikke stoppunkt tilbake i tid for oppfølgingstilfeller som er gyldige nå

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/database/OppfolgingstilfelleArbeidstakerQuery.kt
Ser i proddata at det kan komme oppdateringer på gamle oppfølgingstilfeller, så må først sortere på tilfelle_end for å finne det nyeste.
=> Forbedre logikk for å finne siste oppfølgingstilfelle

src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatStoppunkt.kt
Siste kandidat-batch-kjøring i Arena blir lørdag 17. sept. Setter cutoff til 119 dager før dette, dvs 21. mai 2022.
=> Justere cutoff

src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatStoppunkt.kt, src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
Endre logikken for "gamle" oppfølgingstilfeller slik at stoppunkt-datoen blir dagens dato. Dette er mest for å forenkle testingen - i produksjon vil det bare resultere i at noen blir kandidat en dag før hva de ellers ville blitt.
=> Use stoppunkt today instead of tomorrow

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt, src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt
Siden vi nå har sluttet å lagre oppfølgingstilfellene i isdialogmotekandidat kan vi lage stoppunkt også for tilfeller som starter i framtiden. Men må passe på at vi også håndterer tilfeller som gjelder for dagens dato i tillegg.
=> Create stoppunkt for both current and future tilfelle

src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClientMetric.kt, src/main/kotlin/no/nav/syfo/unntak/UnntakService.kt, src/main/kotlin/no/nav/syfo/unntak/api/UnntakApi.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/SyfoTilgangskontrollMock.kt, src/test/kotlin/no/nav/syfo/unntak/UnntakServiceSpek.kt, src/test/kotlin/no/nav/syfo/unntak/api/UnntakApiSpek.kt
Det kommer av og til noen feil fra `isdialogmotekandidat` fordi den forsøker å hente oppfolgingstilfeller veileder ikke har tilgang til
`io.ktor.client.plugins.ClientRequestException: Client request(GET http://isoppfolgingstilfelle/api/internad/v1/oppfolgingstilfelle/personident) invalid: 403 Forbidden. Text: "Denied NAVIdent access to personIdent: Read OppfolgingstilfelleDTO for Person with PersonIdent"`
Dette kan skyldes at kallet som henter unntaksstatistikk for en veileder spør etter oppfølgingstilfelle for personer som veileder tidligere har satt unntak på, men ikke lenger har tilgang til.
=> Add veiledertilgangskontroll to unntakstatistikk api

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatOutdatedCronjob.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/DialogmotekandidatEndringQuery.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatEndring.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatOutdatedCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Tanken er at jobben finner siste DialogmotekandidatEndring for alle personer. Sjekker så om den er laget før 1.6.2023 og om kandidat=true.
For disse personene lages det en ny DialogmotekandidatEndring med kandidat=false og årsak=LUKKET.
=> Cronjob for outdated dialogmotekandidater

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/client/ClientEnvironment.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/Tilgang.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt, src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/MockHttpClient.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/SyfoTilgangskontrollMock.kt
Bytter fra å bruke syfo-tilgangskontroll til istilgangskontroll
=> IS-1689: Change from syfotilgangskontroll to istilgangskontroll

src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClientMetric.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/api/DialogmotekandidatApi.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatEndring.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/api/DialogmotekandidatApiSpek.kt
Ref beskrivelse i https://github.com/navikt/syfooversiktsrv/pull/352
Endrer i APIet som brukes av syfomodiaperson slik at personen ikke vises som kandidat før det er gått minst syv dager siden personen ble generert som kandidat.
=> IS-2086: Wait seven days before kandidat in api

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatOutdatedCronjob.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/DialogmotekandidatEndringQuery.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/DialogmotekandidatRepository.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatOutdatedCronjobSpek.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjobSpek.kt, src/test/kotlin/no/nav/syfo/dialogmotekandidat/database/DialogmotekandidatRepositorySpek.kt, src/test/kotlin/no/nav/syfo/dialogmotestatusendring/kafka/KafkaDialogmoteStatusEndringServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
- Legger til uuid som skal slettes
- Fantes ikke funksjon som hentet ut fra database basert på `UUID` så måtte legge til dette. Tenkte det var dumt å fortsette på query mønsteret, så la til ny repository fil som kan være utgangspunkt for videre refaktorering.
Todos etter merge
- Sjekk at `syfooversiktsrv` database blir oppdatert
=> IS-2071: Add get dialogmotekandidat from database based on uuid

src/main/kotlin/no/nav/syfo/unntak/UnntakService.kt
Unngå å gjøre kall til isoppfolgingstilfelle midt inni database-transaksjonen
=> IS-2582: Avoid duplicate unntak

.github/dependabot.yaml, README.md, build.gradle.kts, src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt
Sånn at dependabot finner avhengigheter og lagrer ukentige PRs på oppdateringer. Grupperer minor og patch-oppdatering i samme PR.
Gjorde også forenkling av bygge-config inspirert av https://github.com/navikt/isdialogmote/
=> Fix versions and dependabot, simplify build config

src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/api/DialogmotekandidatApi.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/api/HistorikkDTO.kt, src/main/kotlin/no/nav/syfo/ikkeaktuell/IkkeAktuellService.kt, src/main/kotlin/no/nav/syfo/ikkeaktuell/database/IkkeAktuellRepository.kt, src/main/kotlin/no/nav/syfo/ikkeaktuell/database/PIkkeAktuell.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/api/DialogmotekandidatHistorikkApiSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt
Trenger nytt endepunkt for å hente dialogmøtekandidat-historikk (inkl unntak og ikke aktuell-vurderinger) for en person slik at dette kan vises på Historikk-siden i modia.
=> IS-2752: Add endpoint for historikk

src/main/kotlin/no/nav/syfo/unntak/UnntakService.kt, src/main/kotlin/no/nav/syfo/unntak/api/UnntakApi.kt
Kom over en liten forbedring ifm feilsøking av https://trello.com/c/fdQcI5DN/2872-channelwriteexception-i-isoppfolgingstilfelle
Her sender vi potensielt unødvendige duplikater til tilgangskontrollen.
=> IS-2872: Sender unike personidenter til tilgangskontroll

src/main/kotlin/no/nav/syfo/ikkeaktuell/domain/IkkeAktuell.kt
Legger til rette for at disse årsakene skal brukes når det registreres "ikke aktuell" i stedet for "unntak" for dialogmøtekandidat.
Når frontend er tilpasset bør vi gjøre slik at disse årsakene ikke tillates for nye unntak (men vi må beholde de i koden for å kunne hente opp gamle unntak i apiet)
=> IS-2884: Add ikke aktuell-arsaker

build.gradle.kts
Hvis jeg leser dokumentasjonen riktig er det dette som trengs: 
https://github.com/zonkyio/embedded-postgres
Postgres 17.5 er den versjonen vi faktisk bruker på GCP/CloudSQL nå (for alle backend'ene våre).
=> IS-3258: Use correct postgres version in tests
