src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleArbeidstaker.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/database/OppfolgingstilfelleArbeidstakerQuery.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/database/POppfolgingstilfelleArbeidstaker.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfelleArbeidstakerService.kt, src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfelleArbeidstakerServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/KafkaOppfolgingstilfelleArbeidstakerGenerator.kt
Insert OppfolgingstilfelleArbeidstaker from kafka topic in database if
Arbeidstaker is Dialogmotekandidat and if the record is not already
inserted(skipping duplicates).
=> Insert OppfolgingstilfelleArbeidstaker in database

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, build.gradle.kts, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/cronjob/Cronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobResult.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobRunner.kt, src/main/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjobMetric.kt, src/main/kotlin/no/nav/syfo/cronjob/leaderelection/LeaderPodClient.kt, src/main/kotlin/no/nav/syfo/cronjob/leaderelection/LeaderPodDTO.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/DialogmotekandidatStoppunktQuery.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjobSpek.kt, src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfelleArbeidstakerServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmotekandidatStoppunktGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/OppfolgingstilfelleArbeidstakerGenerator.kt
Finner kandidater med stoppunkt planlagt på dagens dato og oppdaterer status (kandidat/ikke-kandidat) avhengig av oppfolgingstilfelle
=> Cronjob for å prosessere dialogmotekandidat-stoppunkt

src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatStoppunkt.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/DialogmotekandidatStoppunktQuery.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/PDialogmotekandidatStoppunkt.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleArbeidstaker.kt, src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfelleArbeidstakerServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmotekandidatStoppunktGenerator.kt
Factory-metode for å opprette DialogmotekandidatStoppunkt med planlagt-status.
=> Flyttet noe logikk relatet til DialogmotekandidatStoppunkt fra OppfolgingstilfelleArbeidstaker

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/DialogmotekandidatStoppunktQuery.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/PDialogmotekandidatStoppunkt.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatStoppunkt.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/DialogmotekandidatEndringProducer.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/KafkaConfig.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/KafkaDialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/KafkaDialogmotekandidatEndringSerializer.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleArbeidstaker.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjobSpek.kt, src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmotekandidatStoppunktGenerator.kt
DialogmotekandidatStoppunkt med status KANDIDAT på planlagt dato skal produsere en DialogmotekandidatEndring til topic
=> Produce DialogmotekandidatEndring from stoppunkt to kafka

src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/DialogmotekandidatEndringQuery.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/DialogmotekandidatStoppunktQuery.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/PDialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatEndring.kt, src/main/resources/db/migration/V1_7__create_table_dialogmotekandidat_endring.sql, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmotekandidatGenerator.kt
Add check for latest endring not kandidat before create and produce endring for stoppunkt-kandidat
=> Persist DialogmotekandidatEndring from stoppunkt-kandidat

src/main/kotlin/no/nav/syfo/cronjob/leaderelection/LeaderPodClient.kt
Ref: https://ktor.io/docs/migrating-2.html#response-validation
=> httpClient expects success

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, build.gradle.kts, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/application/api/ApiPlugins.kt, src/main/kotlin/no/nav/syfo/application/api/auth/ApiAuthenicationPlugin.kt, src/main/kotlin/no/nav/syfo/application/api/auth/JwtIssuer.kt, src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt, src/main/kotlin/no/nav/syfo/client/azuread/AzureAdTokenResponse.kt, src/main/kotlin/no/nav/syfo/client/azuread/AzureEnvironment.kt, src/main/kotlin/no/nav/syfo/client/wellknown/WellKnown.kt, src/main/kotlin/no/nav/syfo/client/wellknown/WellKnownClient.kt, src/main/kotlin/no/nav/syfo/client/wellknown/WellKnownDTO.kt, src/main/kotlin/no/nav/syfo/unntak/api/UnntakApi.kt, src/main/kotlin/no/nav/syfo/util/ObjectMapperConfig.kt, src/main/kotlin/no/nav/syfo/util/RequestUtil.kt, src/test/kotlin/no/nav/syfo/application/api/PodApiSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/JWTUtil.kt, src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/AzureADMock.kt, src/test/kotlin/no/nav/syfo/unntak/api/UnntakApiSpek.kt, src/test/resources/jwkset.json, src/test/resources/logback-test.xml
Foreløpig bare med autentisering og ingen logikk. Veileder-tilgangskontroll og lagring av unntak og kandidat-endring kommer senere.
=> Dummy unntak API

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, gradlew
Bump Gradle, Flyway, Jackson, Kotlin and Ktor version to latest.
=> Bump dependency versions to latest

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
Slik koden er nå så kan man droppe å behandle en liste med oppfølgingstilfeller dersom det finnes en tombstone i lista. Det er bedre å filtrere disse ut før man prosesserer slik det er gjort i en del andre steder både i denne app'en og i andre apper. Se feks KafkaDialogmoteStatusEndringService.
=> Avoid skipping records when a tombstone is in the list

src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleArbeidstaker.kt, src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleArbeidstakerSpek.kt
Kandidat i tidligere oppfølgingstilfelle skal ikke blokkere for at arbeidstakeren blir kandidat på nytt
=> Kandidat i tidligere oppfolgingstilfelle skal ikke blokkere

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePersonService.kt
Ser ut som det går bra, men har generert en million logginnslag på en halv time..
=> Reduce logging

.nais/kafka/dialogmotekandidat.yaml, src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/DialogmotekandidatEndringProducer.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/KafkaDialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/dialogmotestatusendring/kafka/KafkaDialogmoteStatusEndringService.kt, src/main/kotlin/no/nav/syfo/unntak/UnntakService.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjobSpek.kt, src/test/kotlin/no/nav/syfo/dialogmotestatusendring/kafka/KafkaDialogmoteStatusEndringServiceSpek.kt, src/test/kotlin/no/nav/syfo/unntak/api/UnntakApiSpek.kt
Datavarehus-gjengen ønsker å få med to ekstra felter i meldingene på kandidat-topic'en.
=> Tilpasninger for dvh

src/main/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjob.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/database/DialogmotekandidatStoppunktQuery.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjobSpek.kt
Siden cronjob'en kjører hver 4 time kan det dukke opp stoppunkt rett før midnatt som ikke blir fanget opp. Så ta med stoppunkt fra gårsdagen som ikke har blitt prosessert.
=> Include unprocessed stoppunkt from yesterday

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfelleClient.kt, src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfellePersonDTO.kt, src/main/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjob.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/api/DialogmotekandidatApi.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/DialogmotekandidatEndringProducer.kt, src/main/kotlin/no/nav/syfo/dialogmotestatusendring/kafka/KafkaDialogmoteStatusEndringService.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleArbeidstaker.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/database/POppfolgingstilfelleArbeidstaker.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/Oppfolgingstilfelle.kt, src/main/kotlin/no/nav/syfo/unntak/UnntakService.kt, src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjobSpek.kt, src/test/kotlin/no/nav/syfo/dialogmotestatusendring/kafka/KafkaDialogmoteStatusEndringServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Lesing fra isoppfolgingstilfelle er enabled i dev-gcp med denne PR'en, foreløpig skal prod fungere som før.
Neste PR blir enabling i prod og tilpasning av testene.
=> Get oppfolgingstilfelle using api

.github/workflows/dispatch.yaml, .github/workflows/main.yaml, src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfelleClient.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/api/DialogmotekandidatApi.kt, src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt, src/main/kotlin/no/nav/syfo/unntak/UnntakService.kt, src/main/kotlin/no/nav/syfo/unntak/api/UnntakApi.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/OppfolgingstilfelleMock.kt
Bruker obo-token for kallene videre til isoppfolgingstilfelle for tjenestene i veileder-api'et til isdialogmotekandidat.
=> Use obo token

build.gradle.kts
Ville teste om dette funket, gjør livet lettere for _alle de_ som utvikler lokalt på Mac 😬
=> Use postgresEmbedded version based on OS

src/main/kotlin/no/nav/syfo/application/kafka/KafkaConfig.kt
Ser at de kafka-tingene jeg merget i går faktisk feilet, men oppdaget det ikke før nå 🙃  Manglet key-serializer i config.
=> Fix kafka config key-serializer

src/main/resources/db/migration/V2_8__delete_wrong_unntak.sql
Relaterer seg til FAGSYSTEM-263135
=> slett feilregistrert unntak

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Ser ut som vi har manglet disse.
=> Add missing access policy

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatStoppunktCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Set interval delay minutes with environment instead of directly in cronjob class.
=> Run stoppunkt cronjob more frequently in dev

src/main/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatOutdatedCronjob.kt
- Opprydning etter [denne](https://github.com/navikt/isdialogmotekandidat/pull/152)
- Bekreftet oppdatering i `syfooversiktsrv` og `isdialogmotekandidat`.
=> IS-2071-2: Remove updated uuid

src/main/resources/db/migration/V3_3__delete_wrong_unntak.sql
https://jira.adeo.no/browse/FAGSYSTEM-351643
=> IS-2745: delete feilregistrert unntak

src/main/kotlin/no/nav/syfo/cronjob/dialogmotekandidat/DialogmotekandidatOutdatedCronjob.kt
=> IS-2991: Close dialogmotekandidat

src/main/kotlin/no/nav/syfo/unntak/api/domain/CreateUnntakDTO.kt, src/main/kotlin/no/nav/syfo/unntak/api/domain/UnntakDTO.kt, src/main/kotlin/no/nav/syfo/unntak/database/domain/PUnntak.kt, src/main/kotlin/no/nav/syfo/unntak/domain/Unntak.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/UnntakGenerator.kt, src/test/kotlin/no/nav/syfo/unntak/api/UnntakApiSpek.kt
Validerer at årsakene ikke tillates for nye unntak (må beholde enum-verdiene i koden for eksisterende unntak)
OBS merge etter https://github.com/navikt/syfomodiaperson/pull/1621
=> IS-2884: FRISKMELDT and ARBEIDSFORHOLD_OPPHORT not allowed for unntak

build.gradle.kts, src/main/kotlin/no/nav/syfo/dialogmotekandidat/domain/DialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/dialogmotekandidat/kafka/KafkaDialogmotekandidatEndring.kt, src/test/kotlin/no/nav/syfo/ikkeaktuell/api/IkkeAktuellApiSpek.kt, src/test/kotlin/no/nav/syfo/unntak/api/UnntakApiSpek.kt
Legger ved veilederident når dialogmøtekandidatendring er unntak
=> IS-3084: Veilederident for unntak på kafka-topic

src/main/resources/db/migration/V3_4__delete_wrong_unntak.sql
Sletter unntak som ble gjort feilaktig.
https://jira.adeo.no/browse/FAGSYSTEM-373255
=> IS-3176: Delete wrong unntak

src/main/resources/db/migration/V3_5__update_wrong_beskrivelse_for_unntak.sql
Fjerner feil beskrivelse på unntak.
https://jira.adeo.no/browse/FAGSYSTEM-374471
=> IS-3198: Fjerner feil beskrivelse på unntak

src/main/kotlin/no/nav/syfo/identhendelse/kafka/IdenthendelseConsumerService.kt
Støyer i loggene våre. Har dette som warning de fleste andre plasser.
=> IS-3210: Change log-level

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Så at vi manglet dette ettersom Marius gravde i tregheter.
=> IS-3285: Add Telemetry observability

src/main/resources/db/migration/V3_7__update_statistics.sql
Skal merges etter migreringen til Postgres 17
=> IS-3251: Oppdaterer db-statistikk

src/main/kotlin/no/nav/syfo/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/api/DialogmotekandidatDTO.kt, src/main/kotlin/no/nav/syfo/api/endpoints/DialogmotekandidatApi.kt, src/main/kotlin/no/nav/syfo/application/DialogmotekandidatService.kt, src/main/kotlin/no/nav/syfo/application/IOppfolgingstilfelleClient.kt, src/main/kotlin/no/nav/syfo/application/OppfolgingstilfelleService.kt, src/main/kotlin/no/nav/syfo/domain/Dialogmotekandidat.kt, src/main/kotlin/no/nav/syfo/domain/DialogmotekandidatEndring.kt, src/main/kotlin/no/nav/syfo/infrastructure/clients/oppfolgingstilfelle/OppfolgingstilfelleClient.kt, src/test/kotlin/no/nav/syfo/dialogmotekandidat/api/DialogmotekandidatApiSpek.kt
Flytter logikk fra `api` til `application` laget
=> IS-Refactor: Move logic from api to application layer
